_prefs: 
  baselayer: ''
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.58642578125
  - 3.9519408561575946
  - 6
description: Mapping data from Colombia into an interactive map.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: colombia_mapper
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
template: ''
